name: build and release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Build
        run: pnpm build

      - name: Package
        run: pnpm zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            .output/peek-preview-*.zip
          generate_release_notes: true
          draft: false
          prerelease: false
          make_latest: true
